#!/bin/bash

if ! type mocp >/dev/null 2>&1
then
    echo ""
    echo "MOC Is Not Installed!"
    echo ""
    exit 1
fi

MOCSTATE=$(pgrep mocp)

if [[ -z "$MOCSTATE" ]]
then
    echo ""
    echo "MOC Is Not Running!"
    echo ""
    exit 1
fi

# using the sed filter tool to extract values from moc metadata
SONGTITLE=$(mocp -i | grep 'SongTitle:' | sed -e 's/^.*: //');
ARTIST=$(mocp -i | grep 'Artist:' | sed -e 's/^.*: //');
ALBUM=$(mocp -i | grep 'Album:' | sed -e 's/^.*: //');

if [[ -z "$SONGTITLE" ]]
then
    echo ""
    echo "MOC Is Not Playing Anything!"
    echo ""
fi

title=$(echo "$SONGTITLE" | python3 -c "from urllib.parse import quote; print(quote(input()))")
artist=$(echo "$ARTIST" | python3 -c "from urllib.parse import quote; print(quote(input()))")
song=$(curl -s --connect-timeout 30 "https://makeitpersonal.co/lyrics?artist=$artist&title=$title")

echo -e "$SONGTITLE - $ARTIST - $ALBUM\n$song" | vim -
exit 0
